### ISSUE TITLE
Test gui issues thong bao co chuong trinh moi can add vao

### ISSUE THREAD

**Issue by vthanh2823** [devshop2019/Arduino_Hshop#1]
[Ultrasonic_US_015.zip](https://github.com/devshop2019/Arduino_Hshop/files/6685045/Ultrasonic_US_015.zip)

add them chuong trinh test Cam bien sieu am
Vi tri: "cam bien\khoang cach"

**Comment by devshop2019** [comment]
Xac nhan da add!
