### ISSUE TITLE
add them chuong trinh test sieu am

### ISSUE THREAD

**Issue by vthanh2823** [devshop2019/Arduino_Hshop#2]
add vao Arduino_Hshop\libraries\A_Hshop_Test_Hang\examples\Cam_bien\khoang cach\Sieu_am
[Ultrasonic_US_015.zip](https://github.com/devshop2019/Arduino_Hshop/files/6706133/Ultrasonic_US_015.zip)

**Comment by devshop2019** [comment]
OK Thanh, chuong trinh da dc update!
